name: Publish to Modrinth
description: Publish and update Modrinth projects from GitHub
inputs:
  version_name:
    description: The name of this version
    required: false
  version_number:
    description: The version number of this version
    required: true
  version_type:
    description: The type of version
    required: false
    default: release
  changelog:
    description: The changelog for this version
    required: false
  files:
    description: The ZIP files to upload
    required: true
  sync_github:
    description: Whether to sync your GitHub repository with Modrinth
    required: false
outputs:
  url:
    description: The URL of your Modrinth project
runs:
  using: node16
  main: ./src/index.ts